package io.github.pgatzka.stash.pojo.json.items;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public record DataItems2(
        @JsonProperty(value = "accuracyModifier") @Nullable Integer accuracyModifier,
        @JsonProperty(value = "ammoType") @Nullable String ammoType,
        @JsonProperty(value = "armorClass") @Nullable String armorClass,
        @JsonProperty(value = "armorDamage") @Nullable Integer armorDamage,
        @JsonProperty(value = "avg24hPrice") @Nullable Integer avg24hPrice,
        @JsonProperty(value = "backgroundColor", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String backgroundColor,
        @JsonProperty(value = "baseImageLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String baseImageLink,
        @JsonProperty(value = "basePrice", required = true) @JsonSetter(nulls = Nulls.FAIL) int basePrice,
        @JsonProperty(value = "blocksHeadphones") @Nullable Boolean blocksHeadphones,
        @JsonProperty(value = "buyFromTrader", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull BuyFromTrader @NonNull [] buyFromTrader,
        @JsonProperty(value = "categories", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] categories,
        @JsonProperty(value = "changeLast48h") @Nullable Integer changeLast48h,
        @JsonProperty(value = "changeLast48hPercent") @Nullable Double changeLast48hPercent,
        @JsonProperty(value = "conflictingCategories", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] conflictingCategories,
        @JsonProperty(value = "conflictingItems", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] conflictingItems,
        @JsonProperty(value = "conflictingSlotIds", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] conflictingSlotIds,
        @JsonProperty(value = "containsItems", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull ContainsItem @NonNull [] containsItems,
        @JsonProperty(value = "damage") @Nullable Integer damage,
        @JsonProperty(value = "description") @Nullable String description,
        @JsonProperty(value = "discardLimit", required = true) @JsonSetter(nulls = Nulls.FAIL) int discardLimit,
        @JsonProperty(value = "ergonomicsModifier") @Nullable Double ergonomicsModifier,
        @JsonProperty(value = "fragmentationChance") @Nullable Double fragmentationChance,
        @JsonProperty(value = "gridImageLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String gridImageLink,
        @JsonProperty(value = "handbookCategories", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] handbookCategories,
        @JsonProperty(value = "hasGrid") @Nullable Boolean hasGrid,
        @JsonProperty(value = "height", required = true) @JsonSetter(nulls = Nulls.FAIL) int height,
        @JsonProperty(value = "high24hPrice") @Nullable Integer high24hPrice,
        @JsonProperty(value = "iconLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String iconLink,
        @JsonProperty(value = "id", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String id,
        @JsonProperty(value = "image512pxLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String image512pxLink,
        @JsonProperty(value = "image8xLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String image8xLink,
        @JsonProperty(value = "inspectImageLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String inspectImageLink,
        @JsonProperty(value = "lastLowPrice") @Nullable Integer lastLowPrice,
        @JsonProperty(value = "lastOfferCount") @Nullable Integer lastOfferCount,
        @JsonProperty(value = "lastScan") @Nullable String lastScan,
        @JsonProperty(value = "link", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String link,
        @JsonProperty(value = "loudness") @Nullable Integer loudness,
        @JsonProperty(value = "low24hPrice") @Nullable Integer low24hPrice,
        @JsonProperty(value = "maxDurability") @Nullable Integer maxDurability,
        @JsonProperty(value = "minLevelForFlea", required = true) @JsonSetter(nulls = Nulls.FAIL) int minLevelForFlea,
        @JsonProperty(value = "name", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String name,
        @JsonProperty(value = "normalizedName", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String normalizedName,
        @JsonProperty(value = "penetrationPower") @Nullable Integer penetrationPower,
        @JsonProperty(value = "projectileCount") @Nullable Integer projectileCount,
        @JsonProperty(value = "properties") @Nullable Properties properties,
        @JsonProperty(value = "recoil") @Nullable Integer recoil,
        @JsonProperty(value = "recoilModifier") @Nullable Double recoilModifier,
        @JsonProperty(value = "ricochetChance") @Nullable Double ricochetChance,
        @JsonProperty(value = "sellToTrader", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull SellToTrader @NonNull [] sellToTrader,
        @JsonProperty(value = "shortName", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String shortName,
        @JsonProperty(value = "stackMaxSize") @Nullable Integer stackMaxSize,
        @JsonProperty(value = "tracer") @Nullable Boolean tracer,
        @JsonProperty(value = "tracerColor") @Nullable String tracerColor,
        @JsonProperty(value = "types", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String @NonNull [] types,
        @JsonProperty(value = "updated", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String updated,
        @JsonProperty(value = "velocity") @Nullable Double velocity,
        @JsonProperty(value = "weight", required = true) @JsonSetter(nulls = Nulls.FAIL) double weight,
        @JsonProperty(value = "width", required = true) @JsonSetter(nulls = Nulls.FAIL) int width,
        @JsonProperty(value = "wikiLink", required = true) @JsonSetter(nulls = Nulls.FAIL) @NonNull String wikiLink
) {
}
